version: "3"

services:

  db:
    image: postgres:14
    restart: on-failure
    env_file: .env
    volumes:
        - ./database/pg-data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
      
  backend:
    image: ${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}
    depends_on:
      - db
    env_file: 
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    volumes:
      - ./backend:/backend
    ports:
      - "80:8000"
    